# -*- coding: utf-8 -*-
"""primos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e_yew0iCBHGDaOE9i4qjSpindhRZdOfQ
"""

import sys
import bisect
import math

def main():
    data = sys.stdin.read().split()
    if not data:
        return
    t = int(data[0])
    queries = []
    max_b = 0
    idx = 1
    for _ in range(t):
        a = int(data[idx])
        b = int(data[idx + 1])
        idx += 2

        if a > b:
            a, b = b, a
        queries.append((a, b))
        if b > max_b:
            max_b = b
    if max_b < 2:
        primos = []
    else:
        sieve = bytearray(b'\x01') * (max_b + 1)
        sieve[0:2] = b'\x00\x00'
        limit = int(math.isqrt(max_b))
        for i in range(2, limit + 1):
            if sieve[i]:
                start = i * i
                step = i

                sieve[start:max_b + 1:step] = b'\x00' * ((max_b - start) // step + 1)
        primos = [i for i in range(2, max_b + 1) if sieve[i]]
    out_lines = []
    for a, b in queries:
        left = bisect.bisect_left(primes, a)
        right = bisect.bisect_right(primes, b)
        out_lines.append(str(right - left))
    sys.stdout.write("\n".join(out_lines))

if __name__ == "__main__":
    main()